### PR TITLE
fix Pattern-Atlas-Content not aligned with changes in PatternSectionS…

### PR DESCRIPTION
**Pull request by manuwei**
fix issue described in patterpedia-view-backend repo: Pattern-Atlas-Content not aligned with changes in PatternSectionS…

commit testdata that is available under creative commons

### CODE REVIEW

**Review by fakepk — COMMENTED** [review]
## data-qc.sql
-Why is data-qc.sql deleted?

## data-cc.sql
- Try to execute the data-cc.sql files, then you will recognize that the primary key constraint in pattern_section_schema is violated (you use the same PK for all entries)
- why is context section deleted in schema?
- why is solution section deleted in schema?

## data-eip-sql
- in data.eip.sql all the quotes are broken

**Comment by manuwei** [comment]
@fakepk 

# data-qc.sql
I will only commit content to this public repo that is available under creative-commons licence - therefore no Quantum Computing patterns can be commited

# data-cc.sql
- Looks like I commited a wrong file - I fixed this in my previous commit
- As the content/solution section is not available under creative commons, it is not commited (see previous section)  --> https://www.cloudcomputingpatterns.org/copyright/

# data-eip-sql
I don't understand what you mean by 'broken quote'? Did you expect ' instead of "? What is the unwanted behaviour?

**Comment by fakepk** [comment]
For instance the second line in the file:
`INSERT INTO public.pattern_schema (pattern_language_id) VALUES (''54ebf6d5-e9df-44c6-ae31-f84e9bfb2d9f'’);`

should be
`INSERT INTO public.pattern_schema (pattern_language_id) VALUES ('54ebf6d5-e9df-44c6-ae31-f84e9bfb2d9f');`

right?

There are two single quotes in front and after UUID

**Comment by manuwei** [comment]
You're right, the quotes broke when I copy pasted the content of the files into my IDE to commit them- I fixed this in my previous commit

**Comment by fakepk** [comment]
When powering up a completely new database instance and executing data-cc.sql the following error occurs:
[2020-03-26 14:04:49] Detail: Key (id)=(54ebf6d5-e9df-44c6-ae31-f84e9bfb2d9f) already exists.

Doing the same with data-eip.sql results in:
[2020-03-26 14:14:46] Detail: Key (id)=(f6b807aa-5905-4435-aec6-324355a0483f) already exists.

**Pull request merged**
